version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-qunit
    versions:
    - 5.1.3
  - dependency-name: "@clark/eslint-config-ember-typescript"
    versions:
    - 2.0.0
    - 2.1.0
  - dependency-name: "@clark/eslint-config-ember"
    versions:
    - 2.0.0
    - 2.1.0
  - dependency-name: "@clark/eslint-config-node"
    versions:
    - 2.0.0
    - 2.1.0
